image: registry.gitlab.com/islandoftex/images/texlive:latest

stages:
  - build
  - release

build-job:
  stage: build
  only:
    - tags
  script:
    - pdflatex main.tex
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
    - cat main.log
  artifacts:
    paths:
      - main.pdf
    reports:
      dotenv: job.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'main.pdf'
          url: "https://gitlab.com/$CI_PROJECT_PATH/-/jobs/$JOB_ID/artifacts/file/main.pdf"
